name: Build Blog with Shell Commands

on:
  push:
    branches: [main]
    
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js, npm, and pnpm manually
        run: |
          # Download and install nvm:
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          
          # in lieu of restarting the shell
          \. "$HOME/.nvm/nvm.sh"
          
          # Download and install Node.js:
          nvm install 22
          
          # Verify the Node.js version:
          node -v # Should print "v22.17.1".
          nvm current # Should print "v22.17.1".
          
          # Verify npm version:
          npm -v # Should print "10.9.2".
          npm install -g pnpm@latest-10
          pnpm -v
          export PATH=$PATH:$(npm bin -g)
          pnpm install
          pnpm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist  # or ${{ env.BUILD_PATH }}/dist if you’ve set that variable
  deploy:
      needs: build
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
